on:
  pull_request: {}
  push: {}

jobs:
  publish:
    needs: ci
    if:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          app-id: ${{ secrets.BOT_APP_ID }}
      - run: cargo bin makers ci
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  # The ci-matrix job ends up as multiple jobs and therefore as multiple checks.
  # Each check's name ends up with the node version appended.
  # If we were to use those checks as required checks, we would have to occasionally bump them.
  # This job allows us to have a single check that we don't have to bump.
  ci:
    needs: ci-matrix
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  ci-matrix:
    needs: get-supported-node-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.get-supported-node-versions.outputs.versions) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for commit linting
          persist-credentials: false # for later steps to use a different authentication
      - uses: wagoid/commitlint-github-action@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm --global install npm@latest
      - run: npm install
      - run: npm test
  get-supported-node-versions:
    runs-on: ubuntu-latest
    steps:
      - id: get
        uses: msimerson/node-lts-versions@v1.3.3
    outputs:
      versions: ${{ steps.get.outputs.active }}
